name: melos_common_dependencies
description: A package to help manage common dependencies in Melos projects.
version: 0.0.1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  path: ^1.8.3
  yaml: ^3.1.1
  yaml_edit: ^2.1.0

dev_dependencies:
  very_good_analysis:
